# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1404403ad44d95c0709134dbb5226a97fded530ea1f91c2c65acdc2b8b4b8822480e81f8b0d964cffe8f7c8a11c63a3245bb647231013c2c5da77454d1aca6de

test:
  secret_key_base: f927f65d48b524bfca79e3b36ded36c0e65c12ca1b1eba505186723c1d35f2e0fa667c4dcbb462c6cf8862cbdc4084581cd58d77941a5b66b11cc7c800feb322

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
